default_language_version:
  python: python3.10
fail_fast: True
default_stages: [ push ]
repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.4.0
    hooks:
      - id: check-added-large-files
      - id: check-merge-conflict
      - id: end-of-file-fixer
      - id: check-json
      - id: check-xml
      - id: detect-private-key
      - id: no-commit-to-branch
        args: [ '--branch', 'develop' ]
      - id: trailing-whitespace
  - repo: local
    hooks:
      - id: run-rst-lint
        name: Lint rst files ...
        entry: scripts/validate_rst.py
        stages: [ commit ]
        language: python
        always_run: true
      - id: maven-checkstyle
        name: Run checkstyle on Java files ...
        entry: make checkstyle
        stages: [ commit ]
        language: system
        always_run: true
  - repo: https://github.com/ambv/black
    rev: stable
    hooks:
      - id: black
        language_version: python3.10
