default_language_version:
    python: python3.10
fail_fast: True
default_stages: [push]
repos:
    - repo: https://github.com/pre-commit/pre-commit-hooks
      rev: v4.4.0
      hooks:
        - id: check-added-large-files
        - id: check-merge-conflict
        - id: end-of-file-fixer
        - id: check-json
        - id: check-xml
        - id: detect-private-key
        - id: no-commit-to-branch
          args: ['--branch', 'develop']
        - id: trailing-whitespace
    - repo: local
      hooks:
        - id: run-rst-lint
          name: Lint rst files ...
          entry: scripts/validate_rst.py
          stages: [commit]
          language: python
          always_run: true
